# This workflow checks the quality of the code and its coding style, and fails if it finds any errors.

name: flake8 Lint

on:
  push:

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          path: "consang"

      - name: Success message
        if: success()
        run: echo "The workflow has been executed correctly !"
