name: Mirror Push workflow

on:
  push:
  workflow_dispatch:

env:
  MIRROR_URL: "git@github.com:EpitechPGE45-2025/G-ING-900-PAR-9-1-legacy-20.git"

jobs:
  push_to_mirror:
    name: Push New Project Version
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
