name: Mirror push workflow

on:
  workflow_dispatch:

env:
  MIRROR_URL: "git@github.com:LegacyProjectGeneweb/LegacyProject"

jobs:
  push_to_mirror:
    name: Push to mirror
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - repository checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Step 2 - push to mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

      - name: Success message
        if: success()
        run: echo "The workflow has been executed correctly !"
