name: Launch Pytest

on:
  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pytest

      - name: Run pytest
        run: pytest consang/ --maxfail=1 --disable-warnings -q

      - name: Success message
        if: success()
        run: echo "The workflow has been executed correctly !"
